package com.example.museumapp.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.museumapp.bean.OrderRecord;
import com.example.museumapp.bean.User;

import com.example.museumapp.bean.greendao.OrderRecordDao;
import com.example.museumapp.bean.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderRecordDaoConfig;
    private final DaoConfig userDaoConfig;

    private final OrderRecordDao orderRecordDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderRecordDaoConfig = daoConfigMap.get(OrderRecordDao.class).clone();
        orderRecordDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        orderRecordDao = new OrderRecordDao(orderRecordDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(OrderRecord.class, orderRecordDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        orderRecordDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public OrderRecordDao getOrderRecordDao() {
        return orderRecordDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
